// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stellwerk-labs/platform-orchestrator-cp/internal/vault (interfaces: VaultClientInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/vaulter.go -package mock_vault github.com/stellwerk-labs/platform-orchestrator-cp/internal/vault VaultClientInterface
//

// Package mock_vault is a generated GoMock package.
package mock_vault

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVaultClientInterface is a mock of VaultClientInterface interface.
type MockVaultClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockVaultClientInterfaceMockRecorder
	isgomock struct{}
}

// MockVaultClientInterfaceMockRecorder is the mock recorder for MockVaultClientInterface.
type MockVaultClientInterfaceMockRecorder struct {
	mock *MockVaultClientInterface
}

// NewMockVaultClientInterface creates a new mock instance.
func NewMockVaultClientInterface(ctrl *gomock.Controller) *MockVaultClientInterface {
	mock := &MockVaultClientInterface{ctrl: ctrl}
	mock.recorder = &MockVaultClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVaultClientInterface) EXPECT() *MockVaultClientInterfaceMockRecorder {
	return m.recorder
}

// DeleteSecret mocks base method.
func (m *MockVaultClientInterface) DeleteSecret(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockVaultClientInterfaceMockRecorder) DeleteSecret(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockVaultClientInterface)(nil).DeleteSecret), ctx, path)
}

// UpsertSecret mocks base method.
func (m *MockVaultClientInterface) UpsertSecret(ctx context.Context, path string, data map[string]any) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSecret", ctx, path, data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSecret indicates an expected call of UpsertSecret.
func (mr *MockVaultClientInterfaceMockRecorder) UpsertSecret(ctx, path, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSecret", reflect.TypeOf((*MockVaultClientInterface)(nil).UpsertSecret), ctx, path, data)
}
