// Package genevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package genevents

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventType.
const (
	IoPlatformOrchestratorEnvironmentCreated     EventType = "io.platform-orchestrator.environment.created"
	IoPlatformOrchestratorEnvironmentDeleted     EventType = "io.platform-orchestrator.environment.deleted"
	IoPlatformOrchestratorEnvironmentTypeCreated EventType = "io.platform-orchestrator.environment_type.created"
	IoPlatformOrchestratorEnvironmentTypeDeleted EventType = "io.platform-orchestrator.environment_type.deleted"
	IoPlatformOrchestratorEnvironmentTypeUpdated EventType = "io.platform-orchestrator.environment_type.updated"
	IoPlatformOrchestratorEnvironmentUpdated     EventType = "io.platform-orchestrator.environment.updated"
	IoPlatformOrchestratorOrganizationCreated    EventType = "io.platform-orchestrator.organization.created"
	IoPlatformOrchestratorOrganizationDeleted    EventType = "io.platform-orchestrator.organization.deleted"
	IoPlatformOrchestratorOrganizationUpdated    EventType = "io.platform-orchestrator.organization.updated"
	IoPlatformOrchestratorProjectCreated         EventType = "io.platform-orchestrator.project.created"
	IoPlatformOrchestratorProjectDeleted         EventType = "io.platform-orchestrator.project.deleted"
	IoPlatformOrchestratorProjectUpdated         EventType = "io.platform-orchestrator.project.updated"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case IoPlatformOrchestratorEnvironmentCreated:
		return true
	case IoPlatformOrchestratorEnvironmentDeleted:
		return true
	case IoPlatformOrchestratorEnvironmentTypeCreated:
		return true
	case IoPlatformOrchestratorEnvironmentTypeDeleted:
		return true
	case IoPlatformOrchestratorEnvironmentTypeUpdated:
		return true
	case IoPlatformOrchestratorEnvironmentUpdated:
		return true
	case IoPlatformOrchestratorOrganizationCreated:
		return true
	case IoPlatformOrchestratorOrganizationDeleted:
		return true
	case IoPlatformOrchestratorOrganizationUpdated:
		return true
	case IoPlatformOrchestratorProjectCreated:
		return true
	case IoPlatformOrchestratorProjectDeleted:
		return true
	case IoPlatformOrchestratorProjectUpdated:
		return true
	default:
		return false
	}
}

// EnvChangedData defines model for EnvChangedData.
type EnvChangedData struct {
	DeleteRules *bool       `json:"delete_rules,omitempty"`
	EnvId       EnvId       `json:"env_id"`
	EnvTypeId   EnvTypeId   `json:"env_type_id"`
	EnvTypeUuid EnvTypeUuid `json:"env_type_uuid"`
	EnvUuid     EnvUuid     `json:"env_uuid"`
	Force       *bool       `json:"force,omitempty"`
	OrgId       OrgId       `json:"org_id"`
	OrgUuid     OrgUuid     `json:"org_uuid"`
	ProjectId   ProjectId   `json:"project_id"`
	ProjectUuid ProjectUuid `json:"project_uuid"`
	Status      *string     `json:"status,omitempty"`
}

// EnvId defines model for EnvId.
type EnvId = string

// EnvLevelCommonData defines model for EnvLevelCommonData.
type EnvLevelCommonData struct {
	EnvId       EnvId       `json:"env_id"`
	EnvUuid     EnvUuid     `json:"env_uuid"`
	OrgId       OrgId       `json:"org_id"`
	OrgUuid     OrgUuid     `json:"org_uuid"`
	ProjectId   ProjectId   `json:"project_id"`
	ProjectUuid ProjectUuid `json:"project_uuid"`
}

// EnvTypeChangedData defines model for EnvTypeChangedData.
type EnvTypeChangedData struct {
	EnvTypeId   EnvTypeId   `json:"env_type_id"`
	EnvTypeUuid EnvTypeUuid `json:"env_type_uuid"`
	OrgId       OrgId       `json:"org_id"`
	OrgUuid     OrgUuid     `json:"org_uuid"`
}

// EnvTypeId defines model for EnvTypeId.
type EnvTypeId = string

// EnvTypeUuid defines model for EnvTypeUuid.
type EnvTypeUuid = openapi_types.UUID

// EnvUuid defines model for EnvUuid.
type EnvUuid = openapi_types.UUID

// EventType defines model for EventType.
type EventType string

// OrgChangedData defines model for OrgChangedData.
type OrgChangedData = OrgLevelCommonData

// OrgId defines model for OrgId.
type OrgId = string

// OrgLevelCommonData defines model for OrgLevelCommonData.
type OrgLevelCommonData struct {
	OrgId   OrgId   `json:"org_id"`
	OrgUuid OrgUuid `json:"org_uuid"`
}

// OrgUuid defines model for OrgUuid.
type OrgUuid = openapi_types.UUID

// ProjectChangedData defines model for ProjectChangedData.
type ProjectChangedData struct {
	OrgId       OrgId       `json:"org_id"`
	OrgUuid     OrgUuid     `json:"org_uuid"`
	ProjectId   ProjectId   `json:"project_id"`
	ProjectUuid ProjectUuid `json:"project_uuid"`
	Status      *string     `json:"status,omitempty"`
}

// ProjectId defines model for ProjectId.
type ProjectId = string

// ProjectLevelCommonData defines model for ProjectLevelCommonData.
type ProjectLevelCommonData struct {
	OrgId       OrgId       `json:"org_id"`
	OrgUuid     OrgUuid     `json:"org_uuid"`
	ProjectId   ProjectId   `json:"project_id"`
	ProjectUuid ProjectUuid `json:"project_uuid"`
}

// ProjectUuid defines model for ProjectUuid.
type ProjectUuid = openapi_types.UUID
