// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stellwerk-labs/platform-orchestrator-cp/internal/model (interfaces: Databaser,TxWithCommit)
//
// Generated by this command:
//
//	mockgen -destination mocks/databaser.go github.com/stellwerk-labs/platform-orchestrator-cp/internal/model Databaser,TxWithCommit
//

// Package mock_model is a generated GoMock package.
package mock_model

import (
	context "context"
	sql "database/sql"
	json "encoding/json"
	reflect "reflect"

	uuid "github.com/google/uuid"
	reliableoutbox "github.com/stellwerk-labs/golib/hmessaging/reliableoutbox"
	hstandardoutbox "github.com/stellwerk-labs/golib/hstandardoutbox"
	model "github.com/stellwerk-labs/platform-orchestrator-cp/internal/model"
	moduleversions "github.com/stellwerk-labs/platform-orchestrator-cp/internal/moduleversions"
	gomock "go.uber.org/mock/gomock"
)

// MockDatabaser is a mock of Databaser interface.
type MockDatabaser struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaserMockRecorder
	isgomock struct{}
}

// MockDatabaserMockRecorder is the mock recorder for MockDatabaser.
type MockDatabaserMockRecorder struct {
	mock *MockDatabaser
}

// NewMockDatabaser creates a new mock instance.
func NewMockDatabaser(ctrl *gomock.Controller) *MockDatabaser {
	mock := &MockDatabaser{ctrl: ctrl}
	mock.recorder = &MockDatabaserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaser) EXPECT() *MockDatabaserMockRecorder {
	return m.recorder
}

// AcquireModuleOperationReservation mocks base method.
func (m *MockDatabaser) AcquireModuleOperationReservation(ctx context.Context, tx model.Tx, orgID, moduleRef, namespace string, operationID uuid.UUID, relatedResourceID, reason string, actor uuid.UUID) (*model.ModuleOperationReservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireModuleOperationReservation", ctx, tx, orgID, moduleRef, namespace, operationID, relatedResourceID, reason, actor)
	ret0, _ := ret[0].(*model.ModuleOperationReservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcquireModuleOperationReservation indicates an expected call of AcquireModuleOperationReservation.
func (mr *MockDatabaserMockRecorder) AcquireModuleOperationReservation(ctx, tx, orgID, moduleRef, namespace, operationID, relatedResourceID, reason, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireModuleOperationReservation", reflect.TypeOf((*MockDatabaser)(nil).AcquireModuleOperationReservation), ctx, tx, orgID, moduleRef, namespace, operationID, relatedResourceID, reason, actor)
}

// AppendModuleVersionPinNote mocks base method.
func (m *MockDatabaser) AppendModuleVersionPinNote(ctx context.Context, tx model.Tx, orgID string, pinID, actor uuid.UUID, actorType, note string) (*model.ModuleVersionPinEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendModuleVersionPinNote", ctx, tx, orgID, pinID, actor, actorType, note)
	ret0, _ := ret[0].(*model.ModuleVersionPinEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendModuleVersionPinNote indicates an expected call of AppendModuleVersionPinNote.
func (mr *MockDatabaserMockRecorder) AppendModuleVersionPinNote(ctx, tx, orgID, pinID, actor, actorType, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendModuleVersionPinNote", reflect.TypeOf((*MockDatabaser)(nil).AppendModuleVersionPinNote), ctx, tx, orgID, pinID, actor, actorType, note)
}

// AsReliableOutboxStore mocks base method.
func (m *MockDatabaser) AsReliableOutboxStore() reliableoutbox.Store[*hstandardoutbox.PendingEventMessage] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsReliableOutboxStore")
	ret0, _ := ret[0].(reliableoutbox.Store[*hstandardoutbox.PendingEventMessage])
	return ret0
}

// AsReliableOutboxStore indicates an expected call of AsReliableOutboxStore.
func (mr *MockDatabaserMockRecorder) AsReliableOutboxStore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsReliableOutboxStore", reflect.TypeOf((*MockDatabaser)(nil).AsReliableOutboxStore))
}

// BeginTx mocks base method.
func (m *MockDatabaser) BeginTx(ctx context.Context, opts *sql.TxOptions) (model.TxWithCommit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, opts)
	ret0, _ := ret[0].(model.TxWithCommit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockDatabaserMockRecorder) BeginTx(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockDatabaser)(nil).BeginTx), ctx, opts)
}

// BulkDeleteModuleRuleDefinitions mocks base method.
func (m *MockDatabaser) BulkDeleteModuleRuleDefinitions(ctx context.Context, tx model.Tx, orgId string, params model.DeleteModuleRulesParams) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkDeleteModuleRuleDefinitions", ctx, tx, orgId, params)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkDeleteModuleRuleDefinitions indicates an expected call of BulkDeleteModuleRuleDefinitions.
func (mr *MockDatabaserMockRecorder) BulkDeleteModuleRuleDefinitions(ctx, tx, orgId, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkDeleteModuleRuleDefinitions", reflect.TypeOf((*MockDatabaser)(nil).BulkDeleteModuleRuleDefinitions), ctx, tx, orgId, params)
}

// BulkDeleteRunnerRules mocks base method.
func (m *MockDatabaser) BulkDeleteRunnerRules(ctx context.Context, tx model.Tx, orgId string, params model.DeleteRunnerRulesParams) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkDeleteRunnerRules", ctx, tx, orgId, params)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkDeleteRunnerRules indicates an expected call of BulkDeleteRunnerRules.
func (mr *MockDatabaserMockRecorder) BulkDeleteRunnerRules(ctx, tx, orgId, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkDeleteRunnerRules", reflect.TypeOf((*MockDatabaser)(nil).BulkDeleteRunnerRules), ctx, tx, orgId, params)
}

// BulkGetModuleDefinitionVersions mocks base method.
func (m *MockDatabaser) BulkGetModuleDefinitionVersions(ctx context.Context, optionalTx model.Tx, orgId string, defIds, versionIds []string) ([]model.ModuleDefinitionVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkGetModuleDefinitionVersions", ctx, optionalTx, orgId, defIds, versionIds)
	ret0, _ := ret[0].([]model.ModuleDefinitionVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkGetModuleDefinitionVersions indicates an expected call of BulkGetModuleDefinitionVersions.
func (mr *MockDatabaserMockRecorder) BulkGetModuleDefinitionVersions(ctx, optionalTx, orgId, defIds, versionIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkGetModuleDefinitionVersions", reflect.TypeOf((*MockDatabaser)(nil).BulkGetModuleDefinitionVersions), ctx, optionalTx, orgId, defIds, versionIds)
}

// BulkGetResourceTypes mocks base method.
func (m *MockDatabaser) BulkGetResourceTypes(ctx context.Context, optionalTx model.Tx, orgId string, ids []string) ([]model.ResourceType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkGetResourceTypes", ctx, optionalTx, orgId, ids)
	ret0, _ := ret[0].([]model.ResourceType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkGetResourceTypes indicates an expected call of BulkGetResourceTypes.
func (mr *MockDatabaserMockRecorder) BulkGetResourceTypes(ctx, optionalTx, orgId, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkGetResourceTypes", reflect.TypeOf((*MockDatabaser)(nil).BulkGetResourceTypes), ctx, optionalTx, orgId, ids)
}

// Close mocks base method.
func (m *MockDatabaser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDatabaserMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDatabaser)(nil).Close))
}

// CreateEmptyModule mocks base method.
func (m *MockDatabaser) CreateEmptyModule(ctx context.Context, tx model.Tx, orgID, slug, displayName, description, resourceType string, tags map[string]string) (*model.ModuleCatalogue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmptyModule", ctx, tx, orgID, slug, displayName, description, resourceType, tags)
	ret0, _ := ret[0].(*model.ModuleCatalogue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmptyModule indicates an expected call of CreateEmptyModule.
func (mr *MockDatabaserMockRecorder) CreateEmptyModule(ctx, tx, orgID, slug, displayName, description, resourceType, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmptyModule", reflect.TypeOf((*MockDatabaser)(nil).CreateEmptyModule), ctx, tx, orgID, slug, displayName, description, resourceType, tags)
}

// CreateEnvironment mocks base method.
func (m *MockDatabaser) CreateEnvironment(ctx context.Context, optionalTx model.Tx, request *model.Environment) (*model.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEnvironment", ctx, optionalTx, request)
	ret0, _ := ret[0].(*model.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEnvironment indicates an expected call of CreateEnvironment.
func (mr *MockDatabaserMockRecorder) CreateEnvironment(ctx, optionalTx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEnvironment", reflect.TypeOf((*MockDatabaser)(nil).CreateEnvironment), ctx, optionalTx, request)
}

// CreateEnvironmentModuleVersionPin mocks base method.
func (m *MockDatabaser) CreateEnvironmentModuleVersionPin(ctx context.Context, tx model.Tx, orgID string, projectUUID uuid.UUID, projectID string, environmentUUID uuid.UUID, environmentID string, moduleUUID, versionUUID, actor uuid.UUID, actorType, reason string, bulkOperationID *uuid.UUID, allowDefective bool) (*model.EnvironmentModuleVersionPin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEnvironmentModuleVersionPin", ctx, tx, orgID, projectUUID, projectID, environmentUUID, environmentID, moduleUUID, versionUUID, actor, actorType, reason, bulkOperationID, allowDefective)
	ret0, _ := ret[0].(*model.EnvironmentModuleVersionPin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEnvironmentModuleVersionPin indicates an expected call of CreateEnvironmentModuleVersionPin.
func (mr *MockDatabaserMockRecorder) CreateEnvironmentModuleVersionPin(ctx, tx, orgID, projectUUID, projectID, environmentUUID, environmentID, moduleUUID, versionUUID, actor, actorType, reason, bulkOperationID, allowDefective any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEnvironmentModuleVersionPin", reflect.TypeOf((*MockDatabaser)(nil).CreateEnvironmentModuleVersionPin), ctx, tx, orgID, projectUUID, projectID, environmentUUID, environmentID, moduleUUID, versionUUID, actor, actorType, reason, bulkOperationID, allowDefective)
}

// CreateEnvironmentType mocks base method.
func (m *MockDatabaser) CreateEnvironmentType(ctx context.Context, optionalTx model.Tx, request *model.EnvType) (*model.EnvType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEnvironmentType", ctx, optionalTx, request)
	ret0, _ := ret[0].(*model.EnvType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEnvironmentType indicates an expected call of CreateEnvironmentType.
func (mr *MockDatabaserMockRecorder) CreateEnvironmentType(ctx, optionalTx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEnvironmentType", reflect.TypeOf((*MockDatabaser)(nil).CreateEnvironmentType), ctx, optionalTx, request)
}

// CreateModuleDefinition mocks base method.
func (m *MockDatabaser) CreateModuleDefinition(ctx context.Context, optionalTx model.Tx, request *model.ModuleDefinitionVersion) (*model.ModuleDefinitionVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModuleDefinition", ctx, optionalTx, request)
	ret0, _ := ret[0].(*model.ModuleDefinitionVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModuleDefinition indicates an expected call of CreateModuleDefinition.
func (mr *MockDatabaserMockRecorder) CreateModuleDefinition(ctx, optionalTx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModuleDefinition", reflect.TypeOf((*MockDatabaser)(nil).CreateModuleDefinition), ctx, optionalTx, request)
}

// CreateModuleDefinitionVersion mocks base method.
func (m *MockDatabaser) CreateModuleDefinitionVersion(ctx context.Context, tx model.Tx, request *model.ModuleDefinitionVersion) (*model.ModuleDefinitionVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModuleDefinitionVersion", ctx, tx, request)
	ret0, _ := ret[0].(*model.ModuleDefinitionVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModuleDefinitionVersion indicates an expected call of CreateModuleDefinitionVersion.
func (mr *MockDatabaserMockRecorder) CreateModuleDefinitionVersion(ctx, tx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModuleDefinitionVersion", reflect.TypeOf((*MockDatabaser)(nil).CreateModuleDefinitionVersion), ctx, tx, request)
}

// CreateModuleProvider mocks base method.
func (m *MockDatabaser) CreateModuleProvider(ctx context.Context, optionalTx model.Tx, request *model.ModuleProvider) (*model.ModuleProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModuleProvider", ctx, optionalTx, request)
	ret0, _ := ret[0].(*model.ModuleProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModuleProvider indicates an expected call of CreateModuleProvider.
func (mr *MockDatabaserMockRecorder) CreateModuleProvider(ctx, optionalTx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModuleProvider", reflect.TypeOf((*MockDatabaser)(nil).CreateModuleProvider), ctx, optionalTx, request)
}

// CreateModuleRule mocks base method.
func (m *MockDatabaser) CreateModuleRule(ctx context.Context, optionalTx model.Tx, orgId string, request *model.DefinitionRule) (*model.DefinitionRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateModuleRule", ctx, optionalTx, orgId, request)
	ret0, _ := ret[0].(*model.DefinitionRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateModuleRule indicates an expected call of CreateModuleRule.
func (mr *MockDatabaserMockRecorder) CreateModuleRule(ctx, optionalTx, orgId, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateModuleRule", reflect.TypeOf((*MockDatabaser)(nil).CreateModuleRule), ctx, optionalTx, orgId, request)
}

// CreateOrg mocks base method.
func (m *MockDatabaser) CreateOrg(ctx context.Context, optionalTx model.Tx, request *model.Org) (*model.Org, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrg", ctx, optionalTx, request)
	ret0, _ := ret[0].(*model.Org)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrg indicates an expected call of CreateOrg.
func (mr *MockDatabaserMockRecorder) CreateOrg(ctx, optionalTx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrg", reflect.TypeOf((*MockDatabaser)(nil).CreateOrg), ctx, optionalTx, request)
}

// CreateProject mocks base method.
func (m *MockDatabaser) CreateProject(ctx context.Context, optionalTx model.Tx, request *model.Project) (*model.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, optionalTx, request)
	ret0, _ := ret[0].(*model.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockDatabaserMockRecorder) CreateProject(ctx, optionalTx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockDatabaser)(nil).CreateProject), ctx, optionalTx, request)
}

// CreateResourceType mocks base method.
func (m *MockDatabaser) CreateResourceType(ctx context.Context, optionalTx model.Tx, request *model.ResourceType) (*model.ResourceType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResourceType", ctx, optionalTx, request)
	ret0, _ := ret[0].(*model.ResourceType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResourceType indicates an expected call of CreateResourceType.
func (mr *MockDatabaserMockRecorder) CreateResourceType(ctx, optionalTx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResourceType", reflect.TypeOf((*MockDatabaser)(nil).CreateResourceType), ctx, optionalTx, request)
}

// CreateRunner mocks base method.
func (m *MockDatabaser) CreateRunner(ctx context.Context, tx model.Tx, request *model.Runner) (*model.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRunner", ctx, tx, request)
	ret0, _ := ret[0].(*model.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRunner indicates an expected call of CreateRunner.
func (mr *MockDatabaserMockRecorder) CreateRunner(ctx, tx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRunner", reflect.TypeOf((*MockDatabaser)(nil).CreateRunner), ctx, tx, request)
}

// CreateRunnerRule mocks base method.
func (m *MockDatabaser) CreateRunnerRule(ctx context.Context, tx model.Tx, orgId string, request *model.RunnerRule) (*model.RunnerRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRunnerRule", ctx, tx, orgId, request)
	ret0, _ := ret[0].(*model.RunnerRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRunnerRule indicates an expected call of CreateRunnerRule.
func (mr *MockDatabaserMockRecorder) CreateRunnerRule(ctx, tx, orgId, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRunnerRule", reflect.TypeOf((*MockDatabaser)(nil).CreateRunnerRule), ctx, tx, orgId, request)
}

// DeleteEnvironment mocks base method.
func (m *MockDatabaser) DeleteEnvironment(ctx context.Context, optionalTx model.Tx, orgId, projectId, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEnvironment", ctx, optionalTx, orgId, projectId, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEnvironment indicates an expected call of DeleteEnvironment.
func (mr *MockDatabaserMockRecorder) DeleteEnvironment(ctx, optionalTx, orgId, projectId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEnvironment", reflect.TypeOf((*MockDatabaser)(nil).DeleteEnvironment), ctx, optionalTx, orgId, projectId, id)
}

// DeleteEnvironmentType mocks base method.
func (m *MockDatabaser) DeleteEnvironmentType(ctx context.Context, optionalTx model.Tx, orgId, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEnvironmentType", ctx, optionalTx, orgId, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEnvironmentType indicates an expected call of DeleteEnvironmentType.
func (mr *MockDatabaserMockRecorder) DeleteEnvironmentType(ctx, optionalTx, orgId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEnvironmentType", reflect.TypeOf((*MockDatabaser)(nil).DeleteEnvironmentType), ctx, optionalTx, orgId, id)
}

// DeleteModuleDefinition mocks base method.
func (m *MockDatabaser) DeleteModuleDefinition(ctx context.Context, optionalTx model.Tx, orgId, defId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModuleDefinition", ctx, optionalTx, orgId, defId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteModuleDefinition indicates an expected call of DeleteModuleDefinition.
func (mr *MockDatabaserMockRecorder) DeleteModuleDefinition(ctx, optionalTx, orgId, defId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModuleDefinition", reflect.TypeOf((*MockDatabaser)(nil).DeleteModuleDefinition), ctx, optionalTx, orgId, defId)
}

// DeleteModuleDefinitionVersion mocks base method.
func (m *MockDatabaser) DeleteModuleDefinitionVersion(ctx context.Context, optionalTx model.Tx, orgId, defId, versionId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModuleDefinitionVersion", ctx, optionalTx, orgId, defId, versionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteModuleDefinitionVersion indicates an expected call of DeleteModuleDefinitionVersion.
func (mr *MockDatabaserMockRecorder) DeleteModuleDefinitionVersion(ctx, optionalTx, orgId, defId, versionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModuleDefinitionVersion", reflect.TypeOf((*MockDatabaser)(nil).DeleteModuleDefinitionVersion), ctx, optionalTx, orgId, defId, versionId)
}

// DeleteModuleProvider mocks base method.
func (m *MockDatabaser) DeleteModuleProvider(ctx context.Context, optionalTx model.Tx, orgId, providerType, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModuleProvider", ctx, optionalTx, orgId, providerType, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteModuleProvider indicates an expected call of DeleteModuleProvider.
func (mr *MockDatabaserMockRecorder) DeleteModuleProvider(ctx, optionalTx, orgId, providerType, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModuleProvider", reflect.TypeOf((*MockDatabaser)(nil).DeleteModuleProvider), ctx, optionalTx, orgId, providerType, id)
}

// DeleteModuleRule mocks base method.
func (m *MockDatabaser) DeleteModuleRule(ctx context.Context, optionalTx model.Tx, orgId, ruleId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModuleRule", ctx, optionalTx, orgId, ruleId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteModuleRule indicates an expected call of DeleteModuleRule.
func (mr *MockDatabaserMockRecorder) DeleteModuleRule(ctx, optionalTx, orgId, ruleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModuleRule", reflect.TypeOf((*MockDatabaser)(nil).DeleteModuleRule), ctx, optionalTx, orgId, ruleId)
}

// DeleteOrg mocks base method.
func (m *MockDatabaser) DeleteOrg(ctx context.Context, optionalTx model.Tx, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrg", ctx, optionalTx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrg indicates an expected call of DeleteOrg.
func (mr *MockDatabaserMockRecorder) DeleteOrg(ctx, optionalTx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrg", reflect.TypeOf((*MockDatabaser)(nil).DeleteOrg), ctx, optionalTx, id)
}

// DeleteProject mocks base method.
func (m *MockDatabaser) DeleteProject(ctx context.Context, optionalTx model.Tx, orgId, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", ctx, optionalTx, orgId, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockDatabaserMockRecorder) DeleteProject(ctx, optionalTx, orgId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockDatabaser)(nil).DeleteProject), ctx, optionalTx, orgId, id)
}

// DeleteResourceType mocks base method.
func (m *MockDatabaser) DeleteResourceType(ctx context.Context, optionalTx model.Tx, orgId *string, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResourceType", ctx, optionalTx, orgId, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResourceType indicates an expected call of DeleteResourceType.
func (mr *MockDatabaserMockRecorder) DeleteResourceType(ctx, optionalTx, orgId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResourceType", reflect.TypeOf((*MockDatabaser)(nil).DeleteResourceType), ctx, optionalTx, orgId, id)
}

// DeleteRunner mocks base method.
func (m *MockDatabaser) DeleteRunner(ctx context.Context, optionalTx model.Tx, orgId, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRunner", ctx, optionalTx, orgId, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRunner indicates an expected call of DeleteRunner.
func (mr *MockDatabaserMockRecorder) DeleteRunner(ctx, optionalTx, orgId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRunner", reflect.TypeOf((*MockDatabaser)(nil).DeleteRunner), ctx, optionalTx, orgId, id)
}

// DeleteRunnerRule mocks base method.
func (m *MockDatabaser) DeleteRunnerRule(ctx context.Context, optionalTx model.Tx, orgId, ruleId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRunnerRule", ctx, optionalTx, orgId, ruleId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRunnerRule indicates an expected call of DeleteRunnerRule.
func (mr *MockDatabaserMockRecorder) DeleteRunnerRule(ctx, optionalTx, orgId, ruleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRunnerRule", reflect.TypeOf((*MockDatabaser)(nil).DeleteRunnerRule), ctx, optionalTx, orgId, ruleId)
}

// GetCoreModuleVersion mocks base method.
func (m *MockDatabaser) GetCoreModuleVersion(ctx context.Context, optionalTx model.Tx, orgID, moduleRef, versionRef string, mode model.GetMode) (*model.CoreModuleVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoreModuleVersion", ctx, optionalTx, orgID, moduleRef, versionRef, mode)
	ret0, _ := ret[0].(*model.CoreModuleVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoreModuleVersion indicates an expected call of GetCoreModuleVersion.
func (mr *MockDatabaserMockRecorder) GetCoreModuleVersion(ctx, optionalTx, orgID, moduleRef, versionRef, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoreModuleVersion", reflect.TypeOf((*MockDatabaser)(nil).GetCoreModuleVersion), ctx, optionalTx, orgID, moduleRef, versionRef, mode)
}

// GetEnvironment mocks base method.
func (m *MockDatabaser) GetEnvironment(ctx context.Context, optionalTx model.Tx, orgId, projectId, id string, mode model.GetMode) (*model.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironment", ctx, optionalTx, orgId, projectId, id, mode)
	ret0, _ := ret[0].(*model.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironment indicates an expected call of GetEnvironment.
func (mr *MockDatabaserMockRecorder) GetEnvironment(ctx, optionalTx, orgId, projectId, id, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironment", reflect.TypeOf((*MockDatabaser)(nil).GetEnvironment), ctx, optionalTx, orgId, projectId, id, mode)
}

// GetEnvironmentByUuid mocks base method.
func (m *MockDatabaser) GetEnvironmentByUuid(ctx context.Context, optionalTx model.Tx, orgId string, arg3 uuid.UUID, mode model.GetMode) (*model.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironmentByUuid", ctx, optionalTx, orgId, arg3, mode)
	ret0, _ := ret[0].(*model.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironmentByUuid indicates an expected call of GetEnvironmentByUuid.
func (mr *MockDatabaserMockRecorder) GetEnvironmentByUuid(ctx, optionalTx, orgId, arg3, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironmentByUuid", reflect.TypeOf((*MockDatabaser)(nil).GetEnvironmentByUuid), ctx, optionalTx, orgId, arg3, mode)
}

// GetEnvironmentModuleVersionPin mocks base method.
func (m *MockDatabaser) GetEnvironmentModuleVersionPin(ctx context.Context, optionalTx model.Tx, orgID string, pinID uuid.UUID, mode model.GetMode) (*model.EnvironmentModuleVersionPin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironmentModuleVersionPin", ctx, optionalTx, orgID, pinID, mode)
	ret0, _ := ret[0].(*model.EnvironmentModuleVersionPin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironmentModuleVersionPin indicates an expected call of GetEnvironmentModuleVersionPin.
func (mr *MockDatabaserMockRecorder) GetEnvironmentModuleVersionPin(ctx, optionalTx, orgID, pinID, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironmentModuleVersionPin", reflect.TypeOf((*MockDatabaser)(nil).GetEnvironmentModuleVersionPin), ctx, optionalTx, orgID, pinID, mode)
}

// GetEnvironmentType mocks base method.
func (m *MockDatabaser) GetEnvironmentType(ctx context.Context, optionalTx model.Tx, orgId, id string, mode model.GetMode) (*model.EnvType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironmentType", ctx, optionalTx, orgId, id, mode)
	ret0, _ := ret[0].(*model.EnvType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironmentType indicates an expected call of GetEnvironmentType.
func (mr *MockDatabaserMockRecorder) GetEnvironmentType(ctx, optionalTx, orgId, id, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironmentType", reflect.TypeOf((*MockDatabaser)(nil).GetEnvironmentType), ctx, optionalTx, orgId, id, mode)
}

// GetModuleCatalogue mocks base method.
func (m *MockDatabaser) GetModuleCatalogue(ctx context.Context, optionalTx model.Tx, orgID, moduleRef string, mode model.GetMode) (*model.ModuleCatalogue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModuleCatalogue", ctx, optionalTx, orgID, moduleRef, mode)
	ret0, _ := ret[0].(*model.ModuleCatalogue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModuleCatalogue indicates an expected call of GetModuleCatalogue.
func (mr *MockDatabaserMockRecorder) GetModuleCatalogue(ctx, optionalTx, orgID, moduleRef, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModuleCatalogue", reflect.TypeOf((*MockDatabaser)(nil).GetModuleCatalogue), ctx, optionalTx, orgID, moduleRef, mode)
}

// GetModuleCoreCommand mocks base method.
func (m *MockDatabaser) GetModuleCoreCommand(ctx context.Context, optionalTx model.Tx, orgID, scope, key string) (string, json.RawMessage, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModuleCoreCommand", ctx, optionalTx, orgID, scope, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(json.RawMessage)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetModuleCoreCommand indicates an expected call of GetModuleCoreCommand.
func (mr *MockDatabaserMockRecorder) GetModuleCoreCommand(ctx, optionalTx, orgID, scope, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModuleCoreCommand", reflect.TypeOf((*MockDatabaser)(nil).GetModuleCoreCommand), ctx, optionalTx, orgID, scope, key)
}

// GetModuleDefinition mocks base method.
func (m *MockDatabaser) GetModuleDefinition(ctx context.Context, optionalTx model.Tx, orgId, defId string, mode model.GetMode) (*model.ModuleDefinitionVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModuleDefinition", ctx, optionalTx, orgId, defId, mode)
	ret0, _ := ret[0].(*model.ModuleDefinitionVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModuleDefinition indicates an expected call of GetModuleDefinition.
func (mr *MockDatabaserMockRecorder) GetModuleDefinition(ctx, optionalTx, orgId, defId, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModuleDefinition", reflect.TypeOf((*MockDatabaser)(nil).GetModuleDefinition), ctx, optionalTx, orgId, defId, mode)
}

// GetModuleDefinitionVersion mocks base method.
func (m *MockDatabaser) GetModuleDefinitionVersion(ctx context.Context, optionalTx model.Tx, orgId, defId, versionId string) (*model.ModuleDefinitionVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModuleDefinitionVersion", ctx, optionalTx, orgId, defId, versionId)
	ret0, _ := ret[0].(*model.ModuleDefinitionVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModuleDefinitionVersion indicates an expected call of GetModuleDefinitionVersion.
func (mr *MockDatabaserMockRecorder) GetModuleDefinitionVersion(ctx, optionalTx, orgId, defId, versionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModuleDefinitionVersion", reflect.TypeOf((*MockDatabaser)(nil).GetModuleDefinitionVersion), ctx, optionalTx, orgId, defId, versionId)
}

// GetModuleOperationReservation mocks base method.
func (m *MockDatabaser) GetModuleOperationReservation(ctx context.Context, optionalTx model.Tx, orgID string, reservationID uuid.UUID, mode model.GetMode) (*model.ModuleOperationReservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModuleOperationReservation", ctx, optionalTx, orgID, reservationID, mode)
	ret0, _ := ret[0].(*model.ModuleOperationReservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModuleOperationReservation indicates an expected call of GetModuleOperationReservation.
func (mr *MockDatabaserMockRecorder) GetModuleOperationReservation(ctx, optionalTx, orgID, reservationID, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModuleOperationReservation", reflect.TypeOf((*MockDatabaser)(nil).GetModuleOperationReservation), ctx, optionalTx, orgID, reservationID, mode)
}

// GetModuleProvider mocks base method.
func (m *MockDatabaser) GetModuleProvider(ctx context.Context, optionalTx model.Tx, orgId, providerType, id string) (*model.ModuleProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModuleProvider", ctx, optionalTx, orgId, providerType, id)
	ret0, _ := ret[0].(*model.ModuleProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModuleProvider indicates an expected call of GetModuleProvider.
func (mr *MockDatabaserMockRecorder) GetModuleProvider(ctx, optionalTx, orgId, providerType, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModuleProvider", reflect.TypeOf((*MockDatabaser)(nil).GetModuleProvider), ctx, optionalTx, orgId, providerType, id)
}

// GetModuleRule mocks base method.
func (m *MockDatabaser) GetModuleRule(ctx context.Context, optionalTx model.Tx, orgId, ruleId string) (*model.DefinitionRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModuleRule", ctx, optionalTx, orgId, ruleId)
	ret0, _ := ret[0].(*model.DefinitionRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModuleRule indicates an expected call of GetModuleRule.
func (mr *MockDatabaserMockRecorder) GetModuleRule(ctx, optionalTx, orgId, ruleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModuleRule", reflect.TypeOf((*MockDatabaser)(nil).GetModuleRule), ctx, optionalTx, orgId, ruleId)
}

// GetOrg mocks base method.
func (m *MockDatabaser) GetOrg(ctx context.Context, optionalTx model.Tx, id string) (*model.Org, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrg", ctx, optionalTx, id)
	ret0, _ := ret[0].(*model.Org)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrg indicates an expected call of GetOrg.
func (mr *MockDatabaserMockRecorder) GetOrg(ctx, optionalTx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrg", reflect.TypeOf((*MockDatabaser)(nil).GetOrg), ctx, optionalTx, id)
}

// GetProject mocks base method.
func (m *MockDatabaser) GetProject(ctx context.Context, optionalTx model.Tx, orgId, id string, mode model.GetMode) (*model.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, optionalTx, orgId, id, mode)
	ret0, _ := ret[0].(*model.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockDatabaserMockRecorder) GetProject(ctx, optionalTx, orgId, id, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockDatabaser)(nil).GetProject), ctx, optionalTx, orgId, id, mode)
}

// GetProjectByUuid mocks base method.
func (m *MockDatabaser) GetProjectByUuid(ctx context.Context, optionalTx model.Tx, orgId string, arg3 uuid.UUID, mode model.GetMode) (*model.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByUuid", ctx, optionalTx, orgId, arg3, mode)
	ret0, _ := ret[0].(*model.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByUuid indicates an expected call of GetProjectByUuid.
func (mr *MockDatabaserMockRecorder) GetProjectByUuid(ctx, optionalTx, orgId, arg3, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByUuid", reflect.TypeOf((*MockDatabaser)(nil).GetProjectByUuid), ctx, optionalTx, orgId, arg3, mode)
}

// GetResourceType mocks base method.
func (m *MockDatabaser) GetResourceType(ctx context.Context, optionalTx model.Tx, orgId *string, id string) (*model.ResourceType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceType", ctx, optionalTx, orgId, id)
	ret0, _ := ret[0].(*model.ResourceType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceType indicates an expected call of GetResourceType.
func (mr *MockDatabaserMockRecorder) GetResourceType(ctx, optionalTx, orgId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceType", reflect.TypeOf((*MockDatabaser)(nil).GetResourceType), ctx, optionalTx, orgId, id)
}

// GetRunner mocks base method.
func (m *MockDatabaser) GetRunner(ctx context.Context, optionalTx model.Tx, orgId, id string) (*model.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunner", ctx, optionalTx, orgId, id)
	ret0, _ := ret[0].(*model.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunner indicates an expected call of GetRunner.
func (mr *MockDatabaserMockRecorder) GetRunner(ctx, optionalTx, orgId, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunner", reflect.TypeOf((*MockDatabaser)(nil).GetRunner), ctx, optionalTx, orgId, id)
}

// GetRunnerRule mocks base method.
func (m *MockDatabaser) GetRunnerRule(ctx context.Context, optionalTx model.Tx, orgId, ruleId string) (*model.RunnerRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunnerRule", ctx, optionalTx, orgId, ruleId)
	ret0, _ := ret[0].(*model.RunnerRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunnerRule indicates an expected call of GetRunnerRule.
func (mr *MockDatabaserMockRecorder) GetRunnerRule(ctx, optionalTx, orgId, ruleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunnerRule", reflect.TypeOf((*MockDatabaser)(nil).GetRunnerRule), ctx, optionalTx, orgId, ruleId)
}

// InsertPendingEventMessages mocks base method.
func (m *MockDatabaser) InsertPendingEventMessages(ctx context.Context, optionalTx model.Tx, messages []*hstandardoutbox.PendingEventMessage) ([]*hstandardoutbox.PendingEventMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPendingEventMessages", ctx, optionalTx, messages)
	ret0, _ := ret[0].([]*hstandardoutbox.PendingEventMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPendingEventMessages indicates an expected call of InsertPendingEventMessages.
func (mr *MockDatabaserMockRecorder) InsertPendingEventMessages(ctx, optionalTx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPendingEventMessages", reflect.TypeOf((*MockDatabaser)(nil).InsertPendingEventMessages), ctx, optionalTx, messages)
}

// ListAvailableResourceTypes mocks base method.
func (m *MockDatabaser) ListAvailableResourceTypes(ctx context.Context, optionalTx model.Tx, orgId, projectId, envId, pageToken string, perPage int, filters model.ListAvailableResourceTypeParams) ([]model.AvailableResourceType, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailableResourceTypes", ctx, optionalTx, orgId, projectId, envId, pageToken, perPage, filters)
	ret0, _ := ret[0].([]model.AvailableResourceType)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAvailableResourceTypes indicates an expected call of ListAvailableResourceTypes.
func (mr *MockDatabaserMockRecorder) ListAvailableResourceTypes(ctx, optionalTx, orgId, projectId, envId, pageToken, perPage, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailableResourceTypes", reflect.TypeOf((*MockDatabaser)(nil).ListAvailableResourceTypes), ctx, optionalTx, orgId, projectId, envId, pageToken, perPage, filters)
}

// ListCoreModuleVersions mocks base method.
func (m *MockDatabaser) ListCoreModuleVersions(ctx context.Context, optionalTx model.Tx, orgID, moduleRef string, includeDeprecated, includeDefective bool) ([]model.CoreModuleVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCoreModuleVersions", ctx, optionalTx, orgID, moduleRef, includeDeprecated, includeDefective)
	ret0, _ := ret[0].([]model.CoreModuleVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCoreModuleVersions indicates an expected call of ListCoreModuleVersions.
func (mr *MockDatabaserMockRecorder) ListCoreModuleVersions(ctx, optionalTx, orgID, moduleRef, includeDeprecated, includeDefective any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCoreModuleVersions", reflect.TypeOf((*MockDatabaser)(nil).ListCoreModuleVersions), ctx, optionalTx, orgID, moduleRef, includeDeprecated, includeDefective)
}

// ListEnvironmentModuleVersionPins mocks base method.
func (m *MockDatabaser) ListEnvironmentModuleVersionPins(ctx context.Context, optionalTx model.Tx, orgID string, environmentUUID, moduleUUID *uuid.UUID, includeRemoved bool) ([]model.EnvironmentModuleVersionPin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnvironmentModuleVersionPins", ctx, optionalTx, orgID, environmentUUID, moduleUUID, includeRemoved)
	ret0, _ := ret[0].([]model.EnvironmentModuleVersionPin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnvironmentModuleVersionPins indicates an expected call of ListEnvironmentModuleVersionPins.
func (mr *MockDatabaserMockRecorder) ListEnvironmentModuleVersionPins(ctx, optionalTx, orgID, environmentUUID, moduleUUID, includeRemoved any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnvironmentModuleVersionPins", reflect.TypeOf((*MockDatabaser)(nil).ListEnvironmentModuleVersionPins), ctx, optionalTx, orgID, environmentUUID, moduleUUID, includeRemoved)
}

// ListEnvironmentTypes mocks base method.
func (m *MockDatabaser) ListEnvironmentTypes(ctx context.Context, optionalTx model.Tx, orgId, pageToken string, perPage int) ([]model.EnvType, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnvironmentTypes", ctx, optionalTx, orgId, pageToken, perPage)
	ret0, _ := ret[0].([]model.EnvType)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEnvironmentTypes indicates an expected call of ListEnvironmentTypes.
func (mr *MockDatabaserMockRecorder) ListEnvironmentTypes(ctx, optionalTx, orgId, pageToken, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnvironmentTypes", reflect.TypeOf((*MockDatabaser)(nil).ListEnvironmentTypes), ctx, optionalTx, orgId, pageToken, perPage)
}

// ListEnvironments mocks base method.
func (m *MockDatabaser) ListEnvironments(ctx context.Context, optionalTx model.Tx, orgId, projectId, pageToken string, perPage int, params model.ListEnvironmentsParams) ([]model.Environment, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnvironments", ctx, optionalTx, orgId, projectId, pageToken, perPage, params)
	ret0, _ := ret[0].([]model.Environment)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEnvironments indicates an expected call of ListEnvironments.
func (mr *MockDatabaserMockRecorder) ListEnvironments(ctx, optionalTx, orgId, projectId, pageToken, perPage, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnvironments", reflect.TypeOf((*MockDatabaser)(nil).ListEnvironments), ctx, optionalTx, orgId, projectId, pageToken, perPage, params)
}

// ListEnvironmentsByProjectUuid mocks base method.
func (m *MockDatabaser) ListEnvironmentsByProjectUuid(ctx context.Context, optionalTx model.Tx, orgId string, projectUuid uuid.UUID, pageToken string, perPage int) ([]model.Environment, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnvironmentsByProjectUuid", ctx, optionalTx, orgId, projectUuid, pageToken, perPage)
	ret0, _ := ret[0].([]model.Environment)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEnvironmentsByProjectUuid indicates an expected call of ListEnvironmentsByProjectUuid.
func (mr *MockDatabaserMockRecorder) ListEnvironmentsByProjectUuid(ctx, optionalTx, orgId, projectUuid, pageToken, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnvironmentsByProjectUuid", reflect.TypeOf((*MockDatabaser)(nil).ListEnvironmentsByProjectUuid), ctx, optionalTx, orgId, projectUuid, pageToken, perPage)
}

// ListEnvironmentsByRunnerId mocks base method.
func (m *MockDatabaser) ListEnvironmentsByRunnerId(ctx context.Context, optionalTx model.Tx, orgId, runnerId, pageToken string, perPage int) ([]model.Environment, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnvironmentsByRunnerId", ctx, optionalTx, orgId, runnerId, pageToken, perPage)
	ret0, _ := ret[0].([]model.Environment)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEnvironmentsByRunnerId indicates an expected call of ListEnvironmentsByRunnerId.
func (mr *MockDatabaserMockRecorder) ListEnvironmentsByRunnerId(ctx, optionalTx, orgId, runnerId, pageToken, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnvironmentsByRunnerId", reflect.TypeOf((*MockDatabaser)(nil).ListEnvironmentsByRunnerId), ctx, optionalTx, orgId, runnerId, pageToken, perPage)
}

// ListEnvironmentsInOrg mocks base method.
func (m *MockDatabaser) ListEnvironmentsInOrg(ctx context.Context, optionalTx model.Tx, orgId, pageToken string, perPage int, params model.ListEnvironmentsParams) ([]model.Environment, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnvironmentsInOrg", ctx, optionalTx, orgId, pageToken, perPage, params)
	ret0, _ := ret[0].([]model.Environment)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEnvironmentsInOrg indicates an expected call of ListEnvironmentsInOrg.
func (mr *MockDatabaserMockRecorder) ListEnvironmentsInOrg(ctx, optionalTx, orgId, pageToken, perPage, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnvironmentsInOrg", reflect.TypeOf((*MockDatabaser)(nil).ListEnvironmentsInOrg), ctx, optionalTx, orgId, pageToken, perPage, params)
}

// ListModuleCatalogues mocks base method.
func (m *MockDatabaser) ListModuleCatalogues(ctx context.Context, optionalTx model.Tx, orgID string, includeArchived bool) ([]model.ModuleCatalogue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModuleCatalogues", ctx, optionalTx, orgID, includeArchived)
	ret0, _ := ret[0].([]model.ModuleCatalogue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModuleCatalogues indicates an expected call of ListModuleCatalogues.
func (mr *MockDatabaserMockRecorder) ListModuleCatalogues(ctx, optionalTx, orgID, includeArchived any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModuleCatalogues", reflect.TypeOf((*MockDatabaser)(nil).ListModuleCatalogues), ctx, optionalTx, orgID, includeArchived)
}

// ListModuleDefinitionVersions mocks base method.
func (m *MockDatabaser) ListModuleDefinitionVersions(ctx context.Context, optionalTx model.Tx, orgId, defId, pageToken string, perPage int, params model.ListModuleDefinitionVersionsParams) ([]model.ModuleDefinitionVersion, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModuleDefinitionVersions", ctx, optionalTx, orgId, defId, pageToken, perPage, params)
	ret0, _ := ret[0].([]model.ModuleDefinitionVersion)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListModuleDefinitionVersions indicates an expected call of ListModuleDefinitionVersions.
func (mr *MockDatabaserMockRecorder) ListModuleDefinitionVersions(ctx, optionalTx, orgId, defId, pageToken, perPage, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModuleDefinitionVersions", reflect.TypeOf((*MockDatabaser)(nil).ListModuleDefinitionVersions), ctx, optionalTx, orgId, defId, pageToken, perPage, params)
}

// ListModuleDefinitions mocks base method.
func (m *MockDatabaser) ListModuleDefinitions(ctx context.Context, optionalTx model.Tx, orgId, pageToken string, perPage int, params model.ListModuleDefinitionsParams) ([]model.ModuleDefinitionVersion, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModuleDefinitions", ctx, optionalTx, orgId, pageToken, perPage, params)
	ret0, _ := ret[0].([]model.ModuleDefinitionVersion)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListModuleDefinitions indicates an expected call of ListModuleDefinitions.
func (mr *MockDatabaserMockRecorder) ListModuleDefinitions(ctx, optionalTx, orgId, pageToken, perPage, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModuleDefinitions", reflect.TypeOf((*MockDatabaser)(nil).ListModuleDefinitions), ctx, optionalTx, orgId, pageToken, perPage, params)
}

// ListModuleExtensionContributions mocks base method.
func (m *MockDatabaser) ListModuleExtensionContributions(ctx context.Context, optionalTx model.Tx, orgID string, moduleUUID uuid.UUID, includeDraft, includeTerminal bool) ([]model.ModuleExtensionContribution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModuleExtensionContributions", ctx, optionalTx, orgID, moduleUUID, includeDraft, includeTerminal)
	ret0, _ := ret[0].([]model.ModuleExtensionContribution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModuleExtensionContributions indicates an expected call of ListModuleExtensionContributions.
func (mr *MockDatabaserMockRecorder) ListModuleExtensionContributions(ctx, optionalTx, orgID, moduleUUID, includeDraft, includeTerminal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModuleExtensionContributions", reflect.TypeOf((*MockDatabaser)(nil).ListModuleExtensionContributions), ctx, optionalTx, orgID, moduleUUID, includeDraft, includeTerminal)
}

// ListModuleExtensionContributionsForEnvironment mocks base method.
func (m *MockDatabaser) ListModuleExtensionContributionsForEnvironment(ctx context.Context, optionalTx model.Tx, orgID string, environmentUUID uuid.UUID, includeDraft, includeTerminal bool) ([]model.ModuleExtensionContribution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModuleExtensionContributionsForEnvironment", ctx, optionalTx, orgID, environmentUUID, includeDraft, includeTerminal)
	ret0, _ := ret[0].([]model.ModuleExtensionContribution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModuleExtensionContributionsForEnvironment indicates an expected call of ListModuleExtensionContributionsForEnvironment.
func (mr *MockDatabaserMockRecorder) ListModuleExtensionContributionsForEnvironment(ctx, optionalTx, orgID, environmentUUID, includeDraft, includeTerminal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModuleExtensionContributionsForEnvironment", reflect.TypeOf((*MockDatabaser)(nil).ListModuleExtensionContributionsForEnvironment), ctx, optionalTx, orgID, environmentUUID, includeDraft, includeTerminal)
}

// ListModuleLifecycleEvents mocks base method.
func (m *MockDatabaser) ListModuleLifecycleEvents(ctx context.Context, optionalTx model.Tx, orgID, moduleRef, versionRef string) ([]model.ModuleLifecycleEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModuleLifecycleEvents", ctx, optionalTx, orgID, moduleRef, versionRef)
	ret0, _ := ret[0].([]model.ModuleLifecycleEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModuleLifecycleEvents indicates an expected call of ListModuleLifecycleEvents.
func (mr *MockDatabaserMockRecorder) ListModuleLifecycleEvents(ctx, optionalTx, orgID, moduleRef, versionRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModuleLifecycleEvents", reflect.TypeOf((*MockDatabaser)(nil).ListModuleLifecycleEvents), ctx, optionalTx, orgID, moduleRef, versionRef)
}

// ListModuleOperationReservations mocks base method.
func (m *MockDatabaser) ListModuleOperationReservations(ctx context.Context, optionalTx model.Tx, orgID string, moduleUUID uuid.UUID, includeReleased bool) ([]model.ModuleOperationReservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModuleOperationReservations", ctx, optionalTx, orgID, moduleUUID, includeReleased)
	ret0, _ := ret[0].([]model.ModuleOperationReservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModuleOperationReservations indicates an expected call of ListModuleOperationReservations.
func (mr *MockDatabaserMockRecorder) ListModuleOperationReservations(ctx, optionalTx, orgID, moduleUUID, includeReleased any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModuleOperationReservations", reflect.TypeOf((*MockDatabaser)(nil).ListModuleOperationReservations), ctx, optionalTx, orgID, moduleUUID, includeReleased)
}

// ListModuleProviders mocks base method.
func (m *MockDatabaser) ListModuleProviders(ctx context.Context, optionalTx model.Tx, orgId, pageToken string, perPage int, params model.ListModuleProvidersParams) ([]model.ModuleProvider, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModuleProviders", ctx, optionalTx, orgId, pageToken, perPage, params)
	ret0, _ := ret[0].([]model.ModuleProvider)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListModuleProviders indicates an expected call of ListModuleProviders.
func (mr *MockDatabaserMockRecorder) ListModuleProviders(ctx, optionalTx, orgId, pageToken, perPage, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModuleProviders", reflect.TypeOf((*MockDatabaser)(nil).ListModuleProviders), ctx, optionalTx, orgId, pageToken, perPage, params)
}

// ListModuleRules mocks base method.
func (m *MockDatabaser) ListModuleRules(ctx context.Context, optionalTx model.Tx, orgId, pageToken string, perPage int, params model.ListModuleRulesParams) ([]model.DefinitionRule, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModuleRules", ctx, optionalTx, orgId, pageToken, perPage, params)
	ret0, _ := ret[0].([]model.DefinitionRule)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListModuleRules indicates an expected call of ListModuleRules.
func (mr *MockDatabaserMockRecorder) ListModuleRules(ctx, optionalTx, orgId, pageToken, perPage, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModuleRules", reflect.TypeOf((*MockDatabaser)(nil).ListModuleRules), ctx, optionalTx, orgId, pageToken, perPage, params)
}

// ListModuleVersionPinEvents mocks base method.
func (m *MockDatabaser) ListModuleVersionPinEvents(ctx context.Context, optionalTx model.Tx, orgID string, pinID uuid.UUID) ([]model.ModuleVersionPinEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModuleVersionPinEvents", ctx, optionalTx, orgID, pinID)
	ret0, _ := ret[0].([]model.ModuleVersionPinEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModuleVersionPinEvents indicates an expected call of ListModuleVersionPinEvents.
func (mr *MockDatabaserMockRecorder) ListModuleVersionPinEvents(ctx, optionalTx, orgID, pinID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModuleVersionPinEvents", reflect.TypeOf((*MockDatabaser)(nil).ListModuleVersionPinEvents), ctx, optionalTx, orgID, pinID)
}

// ListOrgs mocks base method.
func (m *MockDatabaser) ListOrgs(ctx context.Context, optionalTx model.Tx, pageToken string, perPage int, params model.ListOrgsParams) ([]model.Org, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrgs", ctx, optionalTx, pageToken, perPage, params)
	ret0, _ := ret[0].([]model.Org)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListOrgs indicates an expected call of ListOrgs.
func (mr *MockDatabaserMockRecorder) ListOrgs(ctx, optionalTx, pageToken, perPage, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrgs", reflect.TypeOf((*MockDatabaser)(nil).ListOrgs), ctx, optionalTx, pageToken, perPage, params)
}

// ListProjects mocks base method.
func (m *MockDatabaser) ListProjects(ctx context.Context, optionalTx model.Tx, orgId, pageToken string, perPage int) ([]model.Project, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx, optionalTx, orgId, pageToken, perPage)
	ret0, _ := ret[0].([]model.Project)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockDatabaserMockRecorder) ListProjects(ctx, optionalTx, orgId, pageToken, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockDatabaser)(nil).ListProjects), ctx, optionalTx, orgId, pageToken, perPage)
}

// ListResourceTypes mocks base method.
func (m *MockDatabaser) ListResourceTypes(ctx context.Context, optionalTx model.Tx, orgId *string, pageToken string, perPage int) ([]model.ResourceType, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResourceTypes", ctx, optionalTx, orgId, pageToken, perPage)
	ret0, _ := ret[0].([]model.ResourceType)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListResourceTypes indicates an expected call of ListResourceTypes.
func (mr *MockDatabaserMockRecorder) ListResourceTypes(ctx, optionalTx, orgId, pageToken, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResourceTypes", reflect.TypeOf((*MockDatabaser)(nil).ListResourceTypes), ctx, optionalTx, orgId, pageToken, perPage)
}

// ListRunnerRules mocks base method.
func (m *MockDatabaser) ListRunnerRules(ctx context.Context, optionalTx model.Tx, orgId, pageToken string, perPage int, params model.ListRunnerRulesParams) ([]model.RunnerRule, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRunnerRules", ctx, optionalTx, orgId, pageToken, perPage, params)
	ret0, _ := ret[0].([]model.RunnerRule)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRunnerRules indicates an expected call of ListRunnerRules.
func (mr *MockDatabaserMockRecorder) ListRunnerRules(ctx, optionalTx, orgId, pageToken, perPage, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRunnerRules", reflect.TypeOf((*MockDatabaser)(nil).ListRunnerRules), ctx, optionalTx, orgId, pageToken, perPage, params)
}

// ListRunners mocks base method.
func (m *MockDatabaser) ListRunners(ctx context.Context, optionalTx model.Tx, orgId, pageToken string, perPage int) ([]model.Runner, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRunners", ctx, optionalTx, orgId, pageToken, perPage)
	ret0, _ := ret[0].([]model.Runner)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRunners indicates an expected call of ListRunners.
func (mr *MockDatabaserMockRecorder) ListRunners(ctx, optionalTx, orgId, pageToken, perPage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRunners", reflect.TypeOf((*MockDatabaser)(nil).ListRunners), ctx, optionalTx, orgId, pageToken, perPage)
}

// PublishCoreModuleVersion mocks base method.
func (m *MockDatabaser) PublishCoreModuleVersion(ctx context.Context, tx model.Tx, request *model.ModuleDefinitionVersion, actor uuid.UUID) (*model.CoreModuleVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCoreModuleVersion", ctx, tx, request, actor)
	ret0, _ := ret[0].(*model.CoreModuleVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishCoreModuleVersion indicates an expected call of PublishCoreModuleVersion.
func (mr *MockDatabaserMockRecorder) PublishCoreModuleVersion(ctx, tx, request, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCoreModuleVersion", reflect.TypeOf((*MockDatabaser)(nil).PublishCoreModuleVersion), ctx, tx, request, actor)
}

// PublishStableModuleVersionSuccessor mocks base method.
func (m *MockDatabaser) PublishStableModuleVersionSuccessor(ctx context.Context, tx model.Tx, orgID, moduleRef, prereleaseRef string, expectedPrereleaseVersion int64, reason string, request *model.ModuleDefinitionVersion, actor uuid.UUID) (*model.StableModuleVersionSuccessor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishStableModuleVersionSuccessor", ctx, tx, orgID, moduleRef, prereleaseRef, expectedPrereleaseVersion, reason, request, actor)
	ret0, _ := ret[0].(*model.StableModuleVersionSuccessor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishStableModuleVersionSuccessor indicates an expected call of PublishStableModuleVersionSuccessor.
func (mr *MockDatabaserMockRecorder) PublishStableModuleVersionSuccessor(ctx, tx, orgID, moduleRef, prereleaseRef, expectedPrereleaseVersion, reason, request, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishStableModuleVersionSuccessor", reflect.TypeOf((*MockDatabaser)(nil).PublishStableModuleVersionSuccessor), ctx, tx, orgID, moduleRef, prereleaseRef, expectedPrereleaseVersion, reason, request, actor)
}

// ReleaseModuleOperationReservation mocks base method.
func (m *MockDatabaser) ReleaseModuleOperationReservation(ctx context.Context, tx model.Tx, orgID string, reservationID uuid.UUID, expectedVersion int64, actor uuid.UUID, reason string) (*model.ModuleOperationReservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseModuleOperationReservation", ctx, tx, orgID, reservationID, expectedVersion, actor, reason)
	ret0, _ := ret[0].(*model.ModuleOperationReservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseModuleOperationReservation indicates an expected call of ReleaseModuleOperationReservation.
func (mr *MockDatabaserMockRecorder) ReleaseModuleOperationReservation(ctx, tx, orgID, reservationID, expectedVersion, actor, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseModuleOperationReservation", reflect.TypeOf((*MockDatabaser)(nil).ReleaseModuleOperationReservation), ctx, tx, orgID, reservationID, expectedVersion, actor, reason)
}

// RemoveEnvironmentModuleVersionPinsForDeletion mocks base method.
func (m *MockDatabaser) RemoveEnvironmentModuleVersionPinsForDeletion(ctx context.Context, tx model.Tx, orgID string, environmentUUID, actor uuid.UUID, actorType string) ([]model.EnvironmentModuleVersionPin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveEnvironmentModuleVersionPinsForDeletion", ctx, tx, orgID, environmentUUID, actor, actorType)
	ret0, _ := ret[0].([]model.EnvironmentModuleVersionPin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveEnvironmentModuleVersionPinsForDeletion indicates an expected call of RemoveEnvironmentModuleVersionPinsForDeletion.
func (mr *MockDatabaserMockRecorder) RemoveEnvironmentModuleVersionPinsForDeletion(ctx, tx, orgID, environmentUUID, actor, actorType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEnvironmentModuleVersionPinsForDeletion", reflect.TypeOf((*MockDatabaser)(nil).RemoveEnvironmentModuleVersionPinsForDeletion), ctx, tx, orgID, environmentUUID, actor, actorType)
}

// SetModuleCatalogueStatus mocks base method.
func (m *MockDatabaser) SetModuleCatalogueStatus(ctx context.Context, tx model.Tx, orgID, moduleRef string, target moduleversions.CatalogueStatus, actor uuid.UUID, reason string, expectedVersion int64) (*model.ModuleCatalogue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetModuleCatalogueStatus", ctx, tx, orgID, moduleRef, target, actor, reason, expectedVersion)
	ret0, _ := ret[0].(*model.ModuleCatalogue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetModuleCatalogueStatus indicates an expected call of SetModuleCatalogueStatus.
func (mr *MockDatabaserMockRecorder) SetModuleCatalogueStatus(ctx, tx, orgID, moduleRef, target, actor, reason, expectedVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetModuleCatalogueStatus", reflect.TypeOf((*MockDatabaser)(nil).SetModuleCatalogueStatus), ctx, tx, orgID, moduleRef, target, actor, reason, expectedVersion)
}

// SetResourceTypeCatalogueStatus mocks base method.
func (m *MockDatabaser) SetResourceTypeCatalogueStatus(ctx context.Context, tx model.Tx, orgID, id, target string, actor uuid.UUID, reason string, expectedVersion int64) (*model.ResourceType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetResourceTypeCatalogueStatus", ctx, tx, orgID, id, target, actor, reason, expectedVersion)
	ret0, _ := ret[0].(*model.ResourceType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetResourceTypeCatalogueStatus indicates an expected call of SetResourceTypeCatalogueStatus.
func (mr *MockDatabaserMockRecorder) SetResourceTypeCatalogueStatus(ctx, tx, orgID, id, target, actor, reason, expectedVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetResourceTypeCatalogueStatus", reflect.TypeOf((*MockDatabaser)(nil).SetResourceTypeCatalogueStatus), ctx, tx, orgID, id, target, actor, reason, expectedVersion)
}

// StoreModuleCoreCommand mocks base method.
func (m *MockDatabaser) StoreModuleCoreCommand(ctx context.Context, tx model.Tx, orgID, scope, key, fingerprint string, actor uuid.UUID, response any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreModuleCoreCommand", ctx, tx, orgID, scope, key, fingerprint, actor, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreModuleCoreCommand indicates an expected call of StoreModuleCoreCommand.
func (mr *MockDatabaserMockRecorder) StoreModuleCoreCommand(ctx, tx, orgID, scope, key, fingerprint, actor, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreModuleCoreCommand", reflect.TypeOf((*MockDatabaser)(nil).StoreModuleCoreCommand), ctx, tx, orgID, scope, key, fingerprint, actor, response)
}

// TransitionCoreModuleVersion mocks base method.
func (m *MockDatabaser) TransitionCoreModuleVersion(ctx context.Context, tx model.Tx, orgID, moduleRef, versionRef string, target moduleversions.LifecycleStatus, expectedVersion int64, actor uuid.UUID, reason string, correlationID *uuid.UUID) (*model.CoreModuleVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransitionCoreModuleVersion", ctx, tx, orgID, moduleRef, versionRef, target, expectedVersion, actor, reason, correlationID)
	ret0, _ := ret[0].(*model.CoreModuleVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransitionCoreModuleVersion indicates an expected call of TransitionCoreModuleVersion.
func (mr *MockDatabaserMockRecorder) TransitionCoreModuleVersion(ctx, tx, orgID, moduleRef, versionRef, target, expectedVersion, actor, reason, correlationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransitionCoreModuleVersion", reflect.TypeOf((*MockDatabaser)(nil).TransitionCoreModuleVersion), ctx, tx, orgID, moduleRef, versionRef, target, expectedVersion, actor, reason, correlationID)
}

// TransitionEnvironmentModuleVersionPin mocks base method.
func (m *MockDatabaser) TransitionEnvironmentModuleVersionPin(ctx context.Context, tx model.Tx, orgID string, pinID uuid.UUID, expectedVersion int64, target moduleversions.PinStatus, eventType string, actor uuid.UUID, actorType, reason string, operationID, targetVersionUUID, deploymentID *uuid.UUID) (*model.EnvironmentModuleVersionPin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransitionEnvironmentModuleVersionPin", ctx, tx, orgID, pinID, expectedVersion, target, eventType, actor, actorType, reason, operationID, targetVersionUUID, deploymentID)
	ret0, _ := ret[0].(*model.EnvironmentModuleVersionPin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransitionEnvironmentModuleVersionPin indicates an expected call of TransitionEnvironmentModuleVersionPin.
func (mr *MockDatabaserMockRecorder) TransitionEnvironmentModuleVersionPin(ctx, tx, orgID, pinID, expectedVersion, target, eventType, actor, actorType, reason, operationID, targetVersionUUID, deploymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransitionEnvironmentModuleVersionPin", reflect.TypeOf((*MockDatabaser)(nil).TransitionEnvironmentModuleVersionPin), ctx, tx, orgID, pinID, expectedVersion, target, eventType, actor, actorType, reason, operationID, targetVersionUUID, deploymentID)
}

// UpdateEnvironment mocks base method.
func (m *MockDatabaser) UpdateEnvironment(ctx context.Context, optionalTx model.Tx, orgId, projectId, id string, request *model.EnvironmentPatch) (*model.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEnvironment", ctx, optionalTx, orgId, projectId, id, request)
	ret0, _ := ret[0].(*model.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEnvironment indicates an expected call of UpdateEnvironment.
func (mr *MockDatabaserMockRecorder) UpdateEnvironment(ctx, optionalTx, orgId, projectId, id, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEnvironment", reflect.TypeOf((*MockDatabaser)(nil).UpdateEnvironment), ctx, optionalTx, orgId, projectId, id, request)
}

// UpdateEnvironmentType mocks base method.
func (m *MockDatabaser) UpdateEnvironmentType(ctx context.Context, optionalTx model.Tx, orgId, id string, params model.UpdateEnvTypeParams) (*model.EnvType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEnvironmentType", ctx, optionalTx, orgId, id, params)
	ret0, _ := ret[0].(*model.EnvType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEnvironmentType indicates an expected call of UpdateEnvironmentType.
func (mr *MockDatabaserMockRecorder) UpdateEnvironmentType(ctx, optionalTx, orgId, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEnvironmentType", reflect.TypeOf((*MockDatabaser)(nil).UpdateEnvironmentType), ctx, optionalTx, orgId, id, params)
}

// UpdateModuleCatalogueMetadata mocks base method.
func (m *MockDatabaser) UpdateModuleCatalogueMetadata(ctx context.Context, tx model.Tx, orgID, moduleRef, displayName, description string, tags map[string]string, expectedVersion int64) (*model.ModuleCatalogue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModuleCatalogueMetadata", ctx, tx, orgID, moduleRef, displayName, description, tags, expectedVersion)
	ret0, _ := ret[0].(*model.ModuleCatalogue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateModuleCatalogueMetadata indicates an expected call of UpdateModuleCatalogueMetadata.
func (mr *MockDatabaserMockRecorder) UpdateModuleCatalogueMetadata(ctx, tx, orgID, moduleRef, displayName, description, tags, expectedVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModuleCatalogueMetadata", reflect.TypeOf((*MockDatabaser)(nil).UpdateModuleCatalogueMetadata), ctx, tx, orgID, moduleRef, displayName, description, tags, expectedVersion)
}

// UpdateModuleProvider mocks base method.
func (m *MockDatabaser) UpdateModuleProvider(ctx context.Context, optionalTx model.Tx, request *model.ModuleProvider) (*model.ModuleProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModuleProvider", ctx, optionalTx, request)
	ret0, _ := ret[0].(*model.ModuleProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateModuleProvider indicates an expected call of UpdateModuleProvider.
func (mr *MockDatabaserMockRecorder) UpdateModuleProvider(ctx, optionalTx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModuleProvider", reflect.TypeOf((*MockDatabaser)(nil).UpdateModuleProvider), ctx, optionalTx, request)
}

// UpdateOrg mocks base method.
func (m *MockDatabaser) UpdateOrg(ctx context.Context, optionalTx model.Tx, id string, update model.UpdateOrgRequest) (*model.Org, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrg", ctx, optionalTx, id, update)
	ret0, _ := ret[0].(*model.Org)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrg indicates an expected call of UpdateOrg.
func (mr *MockDatabaserMockRecorder) UpdateOrg(ctx, optionalTx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrg", reflect.TypeOf((*MockDatabaser)(nil).UpdateOrg), ctx, optionalTx, id, update)
}

// UpdateResourceType mocks base method.
func (m *MockDatabaser) UpdateResourceType(ctx context.Context, optionalTx model.Tx, orgId *string, id string, request *model.ResourceTypePatch) (*model.ResourceType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResourceType", ctx, optionalTx, orgId, id, request)
	ret0, _ := ret[0].(*model.ResourceType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResourceType indicates an expected call of UpdateResourceType.
func (mr *MockDatabaserMockRecorder) UpdateResourceType(ctx, optionalTx, orgId, id, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResourceType", reflect.TypeOf((*MockDatabaser)(nil).UpdateResourceType), ctx, optionalTx, orgId, id, request)
}

// UpdateRunner mocks base method.
func (m *MockDatabaser) UpdateRunner(ctx context.Context, optionalTx model.Tx, orgId, id string, request *model.RunnerPatch) (*model.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRunner", ctx, optionalTx, orgId, id, request)
	ret0, _ := ret[0].(*model.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRunner indicates an expected call of UpdateRunner.
func (mr *MockDatabaserMockRecorder) UpdateRunner(ctx, optionalTx, orgId, id, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunner", reflect.TypeOf((*MockDatabaser)(nil).UpdateRunner), ctx, optionalTx, orgId, id, request)
}

// UpdatedProject mocks base method.
func (m *MockDatabaser) UpdatedProject(ctx context.Context, optional model.Tx, orgId, id string, params model.UpdateProjectParams) (*model.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatedProject", ctx, optional, orgId, id, params)
	ret0, _ := ret[0].(*model.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatedProject indicates an expected call of UpdatedProject.
func (mr *MockDatabaserMockRecorder) UpdatedProject(ctx, optional, orgId, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatedProject", reflect.TypeOf((*MockDatabaser)(nil).UpdatedProject), ctx, optional, orgId, id, params)
}

// UpsertModuleExtensionContribution mocks base method.
func (m *MockDatabaser) UpsertModuleExtensionContribution(ctx context.Context, tx model.Tx, orgID, moduleRef string, versionUUID, environmentUUID *uuid.UUID, namespace, externalResourceID, kind, lifecycleState, label, targetURL string, payload map[string]any, actor uuid.UUID) (*model.ModuleExtensionContribution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertModuleExtensionContribution", ctx, tx, orgID, moduleRef, versionUUID, environmentUUID, namespace, externalResourceID, kind, lifecycleState, label, targetURL, payload, actor)
	ret0, _ := ret[0].(*model.ModuleExtensionContribution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertModuleExtensionContribution indicates an expected call of UpsertModuleExtensionContribution.
func (mr *MockDatabaserMockRecorder) UpsertModuleExtensionContribution(ctx, tx, orgID, moduleRef, versionUUID, environmentUUID, namespace, externalResourceID, kind, lifecycleState, label, targetURL, payload, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertModuleExtensionContribution", reflect.TypeOf((*MockDatabaser)(nil).UpsertModuleExtensionContribution), ctx, tx, orgID, moduleRef, versionUUID, environmentUUID, namespace, externalResourceID, kind, lifecycleState, label, targetURL, payload, actor)
}

// MockTxWithCommit is a mock of TxWithCommit interface.
type MockTxWithCommit struct {
	ctrl     *gomock.Controller
	recorder *MockTxWithCommitMockRecorder
	isgomock struct{}
}

// MockTxWithCommitMockRecorder is the mock recorder for MockTxWithCommit.
type MockTxWithCommitMockRecorder struct {
	mock *MockTxWithCommit
}

// NewMockTxWithCommit creates a new mock instance.
func NewMockTxWithCommit(ctrl *gomock.Controller) *MockTxWithCommit {
	mock := &MockTxWithCommit{ctrl: ctrl}
	mock.recorder = &MockTxWithCommitMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxWithCommit) EXPECT() *MockTxWithCommitMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockTxWithCommit) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTxWithCommitMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTxWithCommit)(nil).Commit))
}

// ExecContext mocks base method.
func (m *MockTxWithCommit) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecContext", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecContext indicates an expected call of ExecContext.
func (mr *MockTxWithCommitMockRecorder) ExecContext(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecContext", reflect.TypeOf((*MockTxWithCommit)(nil).ExecContext), varargs...)
}

// QueryContext mocks base method.
func (m *MockTxWithCommit) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryContext", varargs...)
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryContext indicates an expected call of QueryContext.
func (mr *MockTxWithCommitMockRecorder) QueryContext(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryContext", reflect.TypeOf((*MockTxWithCommit)(nil).QueryContext), varargs...)
}

// QueryRowContext mocks base method.
func (m *MockTxWithCommit) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRowContext", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRowContext indicates an expected call of QueryRowContext.
func (mr *MockTxWithCommitMockRecorder) QueryRowContext(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRowContext", reflect.TypeOf((*MockTxWithCommit)(nil).QueryRowContext), varargs...)
}

// Rollback mocks base method.
func (m *MockTxWithCommit) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTxWithCommitMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTxWithCommit)(nil).Rollback))
}
